#ifndef HTML_ELEM_FACTORY_H
#define HTML_ELEM_FACTORY_H

#include "text.h"
#include "a.h"
#include "abbr.h"
#include "acronym.h"
#include "address.h"
#include "applet.h"
#include "area.h"
#include "aside.h"
#include "audio.h"
#include "b.h"
#include "base.h"
#include "basefont.h"
#include "bdi.h"
#include "bdo.h"
#include "big.h"
#include "blockquote.h"
#include "body.h"
#include "br.h"
#include "button.h"
#include "canvas.h"
#include "caption.h"
#include "center.h"
#include "cite.h"
#include "code.h"
#include "col.h"
#include "colgroup.h"
#include "data.h"
#include "datalist.h"
#include "dd.h"
#include "del.h"
#include "details.h"
#include "dfn.h"
#include "dialog.h"
#include "dir.h"
#include "div.h"
#include "dl.h"
#include "dt.h"
#include "em.h"
#include "embed.h"
#include "fieldset.h"
#include "figcaption.h"
#include "figure.h"
#include "font.h"
#include "footer.h"
#include "form.h"
#include "frame.h"
#include "frameset.h"
#include "h1.h"
#include "h2.h"
#include "h3.h"
#include "h4.h"
#include "h5.h"
#include "h6.h"
#include "head.h"
#include "header.h"
#include "hgroup.h"
#include "hr.h"
#include "html.h"
#include "i.h"
#include "iframe.h"
#include "image.h"
#include "img.h"
#include "input.h"
#include "ins.h"
#include "kbd.h"
#include "label.h"
#include "legend.h"
#include "li.h"
#include "link.h"
#include "main.h"
#include "map.h"
#include "mark.h"
#include "marquee.h"
#include "menu.h"
#include "meta.h"
#include "meter.h"
#include "nav.h"
#include "noframes.h"
#include "noscript.h"
#include "object.h"
#include "ol.h"
#include "optgroup.h"
#include "option.h"
#include "output.h"
#include "p.h"
#include "param.h"
#include "picture.h"
#include "pre.h"
#include "progress.h"
#include "q.h"
#include "rp.h"
#include "rt.h"
#include "ruby.h"
#include "s.h"
#include "samp.h"
#include "script.h"
#include "search.h"
#include "section.h"
#include "select.h"
#include "small.h"
#include "source.h"
#include "span.h"
#include "strike.h"
#include "strong.h"
#include "style.h"
#include "sub.h"
#include "summary.h"
#include "sup.h"
#include "svg.h"
#include "table.h"
#include "tbody.h"
#include "td.h"
#include "template.h"
#include "textarea.h"
#include "tfoot.h"
#include "th.h"
#include "thead.h"
#include "time.h"
#include "title.h"
#include "tr.h"
#include "track.h"
#include "tt.h"
#include "u.h"
#include "ul.h"
#include "var.h"
#include "video.h"
#include "wbr.h"
// AUTO-GENERATED

// html_elem factory
class html_elem_factory {
public:
        std::shared_ptr<html_a_elem> a(void);
        std::shared_ptr<html_abbr_elem> abbr(void);
        std::shared_ptr<html_acronym_elem> acronym(void);
        std::shared_ptr<html_address_elem> address(void);
        std::shared_ptr<html_applet_elem> applet(void);
        std::shared_ptr<html_area_elem> area(void);
        std::shared_ptr<html_aside_elem> aside(void);
        std::shared_ptr<html_audio_elem> audio(void);
        std::shared_ptr<html_b_elem> b(void);
        std::shared_ptr<html_base_elem> base(void);
        std::shared_ptr<html_basefont_elem> basefont(void);
        std::shared_ptr<html_bdi_elem> bdi(void);
        std::shared_ptr<html_bdo_elem> bdo(void);
        std::shared_ptr<html_big_elem> big(void);
        std::shared_ptr<html_blockquote_elem> blockquote(void);
        std::shared_ptr<html_body_elem> body(void);
        std::shared_ptr<html_br_elem> br(void);
        std::shared_ptr<html_button_elem> button(void);
        std::shared_ptr<html_canvas_elem> canvas(void);
        std::shared_ptr<html_caption_elem> caption(void);
        std::shared_ptr<html_center_elem> center(void);
        std::shared_ptr<html_cite_elem> cite(void);
        std::shared_ptr<html_code_elem> code(void);
        std::shared_ptr<html_col_elem> col(void);
        std::shared_ptr<html_colgroup_elem> colgroup(void);
        std::shared_ptr<html_data_elem> data(void);
        std::shared_ptr<html_datalist_elem> datalist(void);
        std::shared_ptr<html_dd_elem> dd(void);
        std::shared_ptr<html_del_elem> del(void);
        std::shared_ptr<html_details_elem> details(void);
        std::shared_ptr<html_dfn_elem> dfn(void);
        std::shared_ptr<html_dialog_elem> dialog(void);
        std::shared_ptr<html_dir_elem> dir(void);
        std::shared_ptr<html_div_elem> div(void);
        std::shared_ptr<html_dl_elem> dl(void);
        std::shared_ptr<html_dt_elem> dt(void);
        std::shared_ptr<html_em_elem> em(void);
        std::shared_ptr<html_embed_elem> embed(void);
        std::shared_ptr<html_fieldset_elem> fieldset(void);
        std::shared_ptr<html_figcaption_elem> figcaption(void);
        std::shared_ptr<html_figure_elem> figure(void);
        std::shared_ptr<html_font_elem> font(void);
        std::shared_ptr<html_footer_elem> footer(void);
        std::shared_ptr<html_form_elem> form(void);
        std::shared_ptr<html_frame_elem> frame(void);
        std::shared_ptr<html_frameset_elem> frameset(void);
        std::shared_ptr<html_h1_elem> h1(void);
        std::shared_ptr<html_h2_elem> h2(void);
        std::shared_ptr<html_h3_elem> h3(void);
        std::shared_ptr<html_h4_elem> h4(void);
        std::shared_ptr<html_h5_elem> h5(void);
        std::shared_ptr<html_h6_elem> h6(void);
        std::shared_ptr<html_head_elem> head(void);
        std::shared_ptr<html_header_elem> header(void);
        std::shared_ptr<html_hgroup_elem> hgroup(void);
        std::shared_ptr<html_hr_elem> hr(void);
        std::shared_ptr<html_html_elem> html(void);
        std::shared_ptr<html_i_elem> i(void);
        std::shared_ptr<html_iframe_elem> iframe(void);
        std::shared_ptr<html_image_elem> image(void);
        std::shared_ptr<html_img_elem> img(void);
        std::shared_ptr<html_input_elem> input(void);
        std::shared_ptr<html_ins_elem> ins(void);
        std::shared_ptr<html_kbd_elem> kbd(void);
        std::shared_ptr<html_label_elem> label(void);
        std::shared_ptr<html_legend_elem> legend(void);
        std::shared_ptr<html_li_elem> li(void);
        std::shared_ptr<html_link_elem> link(void);
        std::shared_ptr<html_main_elem> main_elem(void);
        std::shared_ptr<html_map_elem> map(void);
        std::shared_ptr<html_mark_elem> mark(void);
        std::shared_ptr<html_marquee_elem> marquee(void);
        std::shared_ptr<html_menu_elem> menu(void);
        std::shared_ptr<html_meta_elem> meta(void);
        std::shared_ptr<html_meter_elem> meter(void);
        std::shared_ptr<html_nav_elem> nav(void);
        std::shared_ptr<html_noframes_elem> noframes(void);
        std::shared_ptr<html_noscript_elem> noscript(void);
        std::shared_ptr<html_object_elem> object(void);
        std::shared_ptr<html_ol_elem> ol(void);
        std::shared_ptr<html_optgroup_elem> optgroup(void);
        std::shared_ptr<html_option_elem> option(void);
        std::shared_ptr<html_output_elem> output(void);
        std::shared_ptr<html_p_elem> p(void);
        std::shared_ptr<html_param_elem> param(void);
        std::shared_ptr<html_picture_elem> picture(void);
        std::shared_ptr<html_pre_elem> pre(void);
        std::shared_ptr<html_progress_elem> progress(void);
        std::shared_ptr<html_q_elem> q(void);
        std::shared_ptr<html_rp_elem> rp(void);
        std::shared_ptr<html_rt_elem> rt(void);
        std::shared_ptr<html_ruby_elem> ruby(void);
        std::shared_ptr<html_s_elem> s(void);
        std::shared_ptr<html_samp_elem> samp(void);
        std::shared_ptr<html_script_elem> script(void);
        std::shared_ptr<html_search_elem> search(void);
        std::shared_ptr<html_section_elem> section(void);
        std::shared_ptr<html_select_elem> select(void);
        std::shared_ptr<html_small_elem> small(void);
        std::shared_ptr<html_source_elem> source(void);
        std::shared_ptr<html_span_elem> span(void);
        std::shared_ptr<html_strike_elem> strike(void);
        std::shared_ptr<html_strong_elem> strong(void);
        std::shared_ptr<html_style_elem> style(void);
        std::shared_ptr<html_sub_elem> sub(void);
        std::shared_ptr<html_summary_elem> summary(void);
        std::shared_ptr<html_sup_elem> sup(void);
        std::shared_ptr<html_svg_elem> svg(void);
        std::shared_ptr<html_table_elem> table(void);
        std::shared_ptr<html_tbody_elem> tbody(void);
        std::shared_ptr<html_td_elem> td(void);
        std::shared_ptr<html_template_elem> template_elem(void);
        std::shared_ptr<html_textarea_elem> textarea(void);
        std::shared_ptr<html_tfoot_elem> tfoot(void);
        std::shared_ptr<html_th_elem> th(void);
        std::shared_ptr<html_thead_elem> thead(void);
        std::shared_ptr<html_time_elem> time(void);
        std::shared_ptr<html_title_elem> title(void);
        std::shared_ptr<html_tr_elem> tr(void);
        std::shared_ptr<html_track_elem> track(void);
        std::shared_ptr<html_tt_elem> tt(void);
        std::shared_ptr<html_u_elem> u(void);
        std::shared_ptr<html_ul_elem> ul(void);
        std::shared_ptr<html_var_elem> var(void);
        std::shared_ptr<html_video_elem> video(void);
        std::shared_ptr<html_wbr_elem> wbr(void);
        std::shared_ptr<html_text_elem> text(int c);
};

#endif // #ifndef HTML_ELEM_FACTORY_H
